# Generated by Django 6.0.4 on 2026-04-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='me', help_text='Sender name displayed in inbox', max_length=255)),
                ('recipient', models.EmailField(default='me@gmail.com', help_text='Recipient (always yourself)', max_length=255)),
                ('subject', models.CharField(blank=True, default='(no subject)', max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('received_date', models.DateTimeField(help_text='The date shown as "received" in the inbox (user-settable)')),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
    ]
