# Generated by Django 6.0.4 on 2026-04-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(blank=True, default='', help_text='Sender name displayed in inbox', max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
