# Generated by Django 6.0.4 on 2026-04-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='folder',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('drafts', 'Drafts'), ('trash', 'Trash')], default='inbox', max_length=10),
        ),
    ]
