# Generated by Django 6.0.4 on 2026-05-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_email_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sender_email',
            field=models.EmailField(default='sender@example.com', help_text='Sender email address', max_length=255),
        ),
    ]
